services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - .env:/app/.env
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - "**/__pycache__/"
        - action: rebuild
          path: pyproject.toml
